/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 christmas_balls.glb 
Author: Juan Carlos (https://sketchfab.com/grove4069)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/christmas-balls-06e4f260bbf64d2abeca609d78eb164a
Title: Christmas balls!
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Ball(props) {
    const { nodes, materials } = useGLTF('/christmas_balls.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group position={[-0.4, -0.081, -0.076]}>
                    <mesh geometry={nodes.Pallina_natalizia_01_0.geometry} material={materials.Materiale_220} />
                    <mesh geometry={nodes.Pallina_natalizia_01_1.geometry} material={materials.Materiale_221} />
                </group>
                <group position={[-0.234, -0.08, 0.022]}>
                    <group position={[-0.006, 0, -0.098]}>
                        <mesh geometry={nodes.Pallina_natalizia_02_0.geometry} material={materials.Materiale_220} />
                        <mesh geometry={nodes.Pallina_natalizia_02_1.geometry} material={materials.Materiale_226} />
                        <mesh geometry={nodes.Pallina_natalizia_02_2.geometry} material={materials.Materiale_231} />
                        <mesh geometry={nodes.Pallina_natalizia_02_3.geometry} material={materials.Materiale_221} />
                    </group>
                    <mesh geometry={nodes.Gancetto_palline_natalizie_02_0.geometry} material={materials.Materiale_241} />
                </group>
                <group position={[-0.074, -0.08, 0.022]}>
                    <group position={[-0.006, 0, -0.098]}>
                        <mesh geometry={nodes.Pallina_natalizia_03_0.geometry} material={materials.Materiale_234} />
                        <mesh geometry={nodes.Pallina_natalizia_03_1.geometry} material={materials.Materiale_221} />
                    </group>
                    <mesh geometry={nodes.Gancetto_palline_natalizie_03_0.geometry} material={materials.Materiale_241} />
                </group>
                <group position={[-0.394, 0.08, 0.022]}>
                    <group position={[-0.006, -0.001, -0.096]}>
                        <mesh geometry={nodes.Pallina_natalizia_04_0.geometry} material={materials.Materiale_228} />
                        <mesh geometry={nodes.Pallina_natalizia_04_1.geometry} material={materials.Materiale_227} />
                        <mesh geometry={nodes.Pallina_natalizia_04_2.geometry} material={materials.Materiale_229} />
                        <mesh geometry={nodes.Pallina_natalizia_04_3.geometry} material={materials.Materiale_224} />
                    </group>
                    <mesh geometry={nodes.Gancetto_palline_natalizie_04_0.geometry} material={materials.Materiale_241} />
                </group>
                <group position={[-0.234, 0.08, 0.022]}>
                    <group position={[-0.006, -0.001, -0.098]} scale={[0.772, 0.772, 1]}>
                        <mesh geometry={nodes.Pallina_natalizia_05_0.geometry} material={materials.Materiale_226} />
                        <mesh geometry={nodes.Pallina_natalizia_05_1.geometry} material={materials.Materiale_233} />
                        <mesh geometry={nodes.Pallina_natalizia_05_2.geometry} material={materials.Materiale_221} />
                    </group>
                    <mesh geometry={nodes.Gancetto_palline_natalizie_05_0.geometry} material={materials.Materiale_241} />
                </group>
                <group position={[-0.074, 0.08, 0.021]}>
                    <group position={[-0.006, -0.001, -0.098]} scale={0.015}>
                        <mesh geometry={nodes.Filo_intrecciato001_0.geometry} material={materials.Materiale_224} />
                        <mesh geometry={nodes.Filo_intrecciato001_1.geometry} material={materials.Materiale_232} />
                    </group>
                    <group position={[-0.006, -0.001, -0.097]}>
                        <mesh geometry={nodes.Pallina_natalizia_06_0.geometry} material={materials.Materiale_223} />
                        <mesh geometry={nodes.Pallina_natalizia_06_1.geometry} material={materials.Materiale_224} />
                    </group>
                    <mesh geometry={nodes.Gancetto_palline_natalizie_06_0.geometry} material={materials.Materiale_241} />
                </group>
                <group position={[-0.074, 0.239, 0.022]}>
                    <group position={[-0.006, 0, -0.098]}>
                        <mesh geometry={nodes.Pallina_natalizia_09_0.geometry} material={materials.Materiale_236} />
                        <mesh geometry={nodes.Pallina_natalizia_09_1.geometry} material={materials.Materiale_237} />
                    </group>
                    <mesh geometry={nodes.Gancetto_palline_natalizie_09_0.geometry} material={materials.Materiale_241} />
                </group>
                <group position={[-0.234, 0.239, 0.022]}>
                    <group position={[-0.006, 0, -0.098]}>
                        <mesh geometry={nodes.Pallina_natalizia_08_0.geometry} material={materials.Materiale_238} />
                        <mesh geometry={nodes.Pallina_natalizia_08_1.geometry} material={materials.Materiale_221} />
                    </group>
                    <mesh geometry={nodes.Gancetto_palline_natalizie_08_0.geometry} material={materials.Materiale_241} />
                </group>
                <group position={[-0.394, 0.239, 0.022]}>
                    <group position={[-0.006, 0, -0.098]}>
                        <mesh geometry={nodes.Pallina_natalizia_07_0.geometry} material={materials.Materiale_220} />
                        <mesh geometry={nodes.Pallina_natalizia_07_1.geometry} material={materials.Materiale_225} />
                        <mesh geometry={nodes.Pallina_natalizia_07_2.geometry} material={materials.Materiale_230} />
                        <mesh geometry={nodes.Pallina_natalizia_07_3.geometry} material={materials.Materiale_221} />
                    </group>
                    <mesh geometry={nodes.Gancetto_palline_natalizie_07_0.geometry} material={materials.Materiale_241} />
                </group>
                <group position={[-0.394, 0.401, 0.022]}>
                    <group position={[-0.006, -0.001, -0.098]}>
                        <mesh geometry={nodes.Pallina_natalizia_10_0.geometry} material={materials.Materiale_235} />
                        <mesh geometry={nodes.Pallina_natalizia_10_1.geometry} material={materials.Materiale_224} />
                    </group>
                    <mesh geometry={nodes.Gancetto_palline_natalizie_10_0.geometry} material={materials.Materiale_241} />
                </group>
                <group position={[-0.234, 0.401, 0.022]}>
                    <mesh geometry={nodes.Gancetto_palline_natalizie_11_0.geometry} material={materials.Materiale_241} />
                    <mesh geometry={nodes.Pallina_natalizia_11_0.geometry} material={materials.Materiale_224} position={[-0.006, -0.001, -0.098]} />
                </group>
                <group position={[-0.074, 0.401, 0.022]}>
                    <group position={[-0.006, -0.001, -0.022]}>
                        <mesh geometry={nodes.Pallina_natalizzia_12_0.geometry} material={materials.Materiale_224} />
                        <mesh geometry={nodes.Pallina_natalizzia_12_1.geometry} material={materials.Materiale_229} />
                        <mesh geometry={nodes.Pallina_natalizzia_12_2.geometry} material={materials.Materiale_239} />
                        <mesh geometry={nodes.Pallina_natalizzia_12_3.geometry} material={materials.Materiale_240} />
                    </group>
                    <mesh geometry={nodes.Gancetto_palline_natalizie_12_0.geometry} material={materials.Materiale_241} />
                </group>
                <mesh geometry={nodes.Gancetto_palline_natalizie_01_0.geometry} material={materials.Materiale_241} position={[-0.394, -0.08, 0.022]} />
            </group>
        </group>
    )
}

useGLTF.preload('/christmas_balls.glb')
