/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tree1.glb 
Author: rhcreations (https://sketchfab.com/rhcreations)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pine-tree-2-4fcec3506f964a3e82741b9c2b7fc3f8
Title: Pine Tree 2
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree(props) {
  const { nodes, materials } = useGLTF('/tree1.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-1.611, -1.013, -1.605]} scale={[2.504, 3.777, 3.777]}>
          <mesh geometry={nodes.Pine_Tree_2_0.geometry} material={materials.Pine_Needles} />
          <mesh geometry={nodes.Pine_Tree_2_1.geometry} material={materials.Bark_Material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tree1.glb')
